env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/essential
  - plugin:@typescript-eslint/recommended
parser: 'vue-eslint-parser'
plugins:
  - vue
  - '@typescript-eslint'
